logging:
  level:
    com.felix.general.code: debug
  config: classpath:log4j2-spring.xml


spring:
  datasource:
    name: general_code_db
    url: jdbc:mysql://172.28.195.72:3306/general_code
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  data:
    redis:
      host: 172.28.195.72
      port: 6379
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8
      password: root
